version: '3.7'
services:
 frontend:
  image: frontend
  build:
   context: ./frontend/
   dockerfile: Dockerfile
  ports:
   - 80:80
  volumes:
   - ./frontend/:/apps/test-bravi/frontend/
  depends_on:
   - mysql
  networks:
   - bravi-network
 backend:
  image: backend
  build:
   context: ./backend/
   dockerfile: Dockerfile
  ports:
   - 5000:5000
  depends_on:
   - mysql
  expose:
   - "5000"
  networks:
   - bravi-network
  environment:
   MYSQL_HOST: "mysql"
 mysql:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  ports:
   - 3306:3306
  expose:
   - "3306"
  environment:
   MYSQL_ROOT_PASSWORD: "123456"
  volumes:
    - ./database/prepare-db/:/docker-entrypoint-initdb.d/
    - ./database/persistence:/var/lib/mysql
  networks:
   - bravi-network

networks:
 bravi-network:
  driver: bridge
