version: '3.7'
services:
 frontend:
  image: frontend
  build:
   context: ./frontend/
   dockerfile: Dockerfile
  ports:
   - 80:80
  volumes:
   - ./frontend/:/apps/test-contacts/frontend/
  depends_on:
   - mysql-db
   - backend
  networks:
   - contacts-network
 backend:
  image: backend
  build:
   context: ./backend/
   dockerfile: Dockerfile
  ports:
   - 5000:5000
  depends_on:
   - mysql-db
  expose:
   - "5000"
  networks:
   - contacts-network
  environment:
   MYSQL_HOST: "mysql-db"
 mysql-db:
  image: mysql:5.7.22
  command: ['--default-authentication-plugin=mysql_native_password', '--log_error_verbosity=1']
  restart: always
  ports:
   - 3306:3306
  expose:
   - "3306"
  environment:
   MYSQL_ROOT_PASSWORD: "123456"
  volumes:
    - ./database/prepare-db/:/docker-entrypoint-initdb.d/
    - ./database/persistence:/var/lib/mysql
  networks:
   - contacts-network

networks:
 contacts-network:
  driver: bridge
