version: '3.1'
services:
 frontend:
  build: ./frontend
  image: nginx
  ports:
   - 80:80
  volumes:
   - ./frontend/:/apps/test-bravi/frontend/
   - ./frontend/config/nginx:/etc/nginx/sites-enabled
  depends_on:
   - mysql
   - backend
 backend:
  build: ./backend/
  image: node:10.0.0
  working_dir: /apps/test-bravi/backend
  ports:
   - 5000:5000
  tty: true
  command: npm start
  environment:
   MYSQL_HOST: mysql
   MYSQL_PORT: 3306
   MYSQL_USER: bravi-user
   MYSQL_PASSWORD: 123456
  depends_on:
   - mysql
 mysql:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  ports:
   - 3306:3306
  environment:
   MYSQL_ROOT_PASSWORD: 123456
   MYSQL_DATABASE: 'bravi-test'
   MYSQL_USER: 'bravi-user'
   MYSQL_PASSWORD: '123456'
   MYSQL_ROOT_HOST: '%'
  restart: always
  volumes:
    - ./database/prepare-db/:/docker-entrypoint-initdb.d/
    - ./database/persistence:/var/lib/mysql